wandb/llm-leaderboard

Dockerfile

Revert "Delete Dockerfile"

---

scripts/cleanup.py
scripts/run_eval.py

Description:
This pull request addresses an issue where the wandb.init function was failing due to improper configuration loading prior to its invocation. The problem was identified when attempting to use wandb.launch to run jobs, which resulted in errors due to the inability to parse the expected commit object in the Git repository.
Changes made:
- Ensured that the configuration file configs/config.yaml is correctly loaded and validated before initializing a wandb run.
- Added checks to confirm the presence of the configuration file and its successful conversion to a dictionary object, which is required by wandb.init.
- Implemented a fallback mechanism to write the runtime configuration to configs/config.yaml if the file does not exist, ensuring that wandb.launch can reference it …

Fix Configuration Loading Issue for wandb.launch Compatibility

---

README.md
configs/gpt3.5turbo.yaml
configs/mistral7b.yaml
requirements.txt
scripts/mtbench_eval.py

Add AVG_mtbench 

---

requirements.txt

update Anthropic version

---

scripts/mtbench_eval.py

- Add support for multi-turn matches with repeated questions and answers for each judge. 
- Updated data processing to repeat entries based on the number of judges and correctly assign questions and answers to each turn.

Add multi judge

---

configs/config_prototype.yaml
scripts/test_chat_template.py
scripts/utils.py
scripts/vllm_server.py

- scripts/utils.py
- tokenizer_configの取得を関数化
- scripts/vllm_server.py
- tokenizer_configをsetする部分を関数を使ってリファクタ
- scripts/test_chat_template.py
- chat_templateをtestする関数を作成

tokenizer_config取得のリファクタとchat_templateのtestスクリプトの作成

---

README.md
configs/config-llama-3-8b-instruct.yaml
configs/config_prototype.yaml
configs/config_template.yaml
configs/gpt3.5turbo.yaml
configs/mistral7b.yaml
scripts/mtbench_eval.py

Typo anthoropic

---

scripts/evaluator/evaluate_utils/__init__.py

`scripts/evaluator/evaluate_utils/__init__.py`でimportできていない関数があったので修正させていただきました。

fix around __init__.py

---

configs/base_config.yaml
requirements.txt
scripts/evaluator/evaluate_utils/__init__.py
scripts/evaluator/jbbq.py
scripts/evaluator/lctg.py
scripts/fastchat/llm_judge/gen_api_answer.py
scripts/llm_inference_adapter.py

openai/gpt-4oにてjbbqを除くデータセットが回るよう軽微な修正を行いました

Minor fixes

---

scripts/utils.py
scripts/vllm_server.py

- run=Noneのときに別のrunのartifactがreadできなかったので修正いたしました。
- Local LLMにてrequestのlogを非表示にしました。

Minor updates

---

scripts/evaluator/jaster.py

- Fix text_formatter
- Change the parameters passed to text_formatter

Fix text_formatter

---

scripts/aggregate.py

MTBenchのstemに倣って、jmmlu_stemをQAの集計に移動

jmmlu_stemをQAの集計に移動

---

scripts/evaluator/jaster.py
scripts/evaluator/lctg.py

Changed to pass message to input instead of prompt

Fix inputs prompt

---

scripts/evaluator/evaluate_utils/formatter.py
scripts/evaluator/evaluate_utils/robustness.py
scripts/evaluator/jaster.py

symbolとincorrectのoutputが表示されない問題をfix
クエリの間違い、データごとのnormal, symbol, incorectの対応付けで解決

Bug fix robustness

---

scripts/aggregate.py
scripts/evaluator/lctg.py

- Fix typo "AVG_Total-ctg" to "AVG_Total_ctg"
- Fix lctg_overall columns "Total-AVG-ctg" to "AVG_Total_ctg"

Fix params and typo

---

scripts/aggregate.py

model release dateをdatetime型に変更

model release dateをdatetime型に変更

---

scripts/evaluator/evaluate_utils/llm_async_processor.py

invoke時にlistではなくstringを渡してしまうバグがあったのでdataのtypeをチェックするメソッドを追加

Add assertion of messages in generation of output

---

scripts/aggregate.py

Fix around columns of leaderboard table

---

chat_templates/Qwen/Qwen2-1.5B-Instruct.jinja
chat_templates/Qwen/Qwen2-72B-Instruct.jinja
chat_templates/Qwen/Qwen2-7B-Instruct.jinja
configs/config-google-gemini-1-5-flash.yaml
configs/config-mistral-mistral-small.yaml
configs/config-tokyotech-llm-Swallow-MS-7b-v0.1.yaml

- jinja
- chat_templates/Qwen/Qwen2-1.5B-Instruct.jinja
- chat_templates/Qwen/Qwen2-72B-Instruct.jinja
- chat_templates/Qwen/Qwen2-7B-Instruct.jinja
- config
- configs/config-google-gemini-1-5-flash.yaml
- configs/config-mistral-mistral-small.yaml
- configs/config-tokyotech-llm-Swallow-MS-7b-v0.1.yaml

Add some jinja files and config

---

scripts/evaluator/jaster.py

Modify mmlu_en intro

---

scripts/evaluator/aggregate.py

Add create_subcategory_table

---

scripts/evaluator/aggregate.py

Move AVG to the top

---

scripts/evaluator/aggregate.py
scripts/evaluator/jaster.py

- Fixed the number of questions being tripled
- Fixed task mismatch between dfs
- Add mgsm to mathematical reasoning

Fix robust dataframe order

---

configs/config-Meta-Llama-3-70B-Instruct.yaml
configs/config-Meta-Llama-3-8B-Instruct.yaml
configs/config-Mistral-7B-Instruct-v0-2.yaml
configs/config-Mixtral-8x7B-Instruct-v0-1.yaml
configs/config-Qwen1-5-72B-Chat.yaml
configs/config-RakutenAI-7B-chat.yaml
configs/config-Swallow-MS-7b-instruct-v0-1.yaml
configs/config-Swallow-MS-7b-v0-1.yaml
configs/config-Yi-34B-Chat.yaml
configs/config-anthropic-claude-3-opus-20240229-v1:0.yaml
configs/config-cyberagent-calm2-7b-chat.yaml
configs/config-google-gemini-1-5-flash.yaml
configs/config-google-gemini-1-5-pro.yaml
configs/config-gpt-3-5-turbo-0125.yaml
configs/config-gpt-4-0613.yaml
configs/config-gpt-4-turbo-2024-04-09.yaml
configs/config-gpt-4o-2024-05-13.yaml
configs/config-llm-jp-13b-instruct-full-dolly-ichikara_004_001_single-oasst-oasst2-v2-0.yaml
configs/config-mistral-large.yaml
configs/config-mistral-small.yaml
scripts/evaluator/aggregate.py

**Description:**
This PR introduces updates to the configuration file by adding `model.size` and `model.size_category` fields. Additionally, it modifies the behavior when saving tables to use `np.nan` as the default value for missing entries. These changes ensure better handling of model specifications and data integrity during table operations.

 Add `model.size` and `model.size_category` to Config and Set Default Value for np.nan on Table Save

---

scripts/evaluator/evaluate_utils/metrics.py
scripts/evaluator/jaster.py

- Fix is_all_digit
- Changed so that decimals and negative numbers are also accepted as correct answers
- exact_match_figure
- Ignore the difference between decimals and integers

Fix is_all_digit and add exact_match_figure

---

configs/base_config.yaml

before
質問を入力とし、回答を出力してください。回答の他には何も含めないことを厳守してください。
after
質問を入力とし、数字のみの回答を出力してください。回答の他には何も含めないことを厳守してください。

Update jaster version for mgsm instruct modify

---

.gitignore
scripts/evaluator/jbbq.py

JBBQにいくつかの列を追加
関係ない出力を出したときにそれをbias scoreの算出に含めないようにするロジックを追加

Modify some columns to JBBQ

---

scripts/evaluator/toxicity.py

This PR addresses an issue in `toxicity.py` where the parsing of Booleans to integers was not included in the retry mechanism, leading to occasional errors. The fix ensures that this conversion is now properly retried in case of failures, enhancing the robustness of the error handling process.
The changes have been thoroughly tested with two models, `gpt-4o` and `cyberagent/calm2-7b-chat`, to confirm that the functionality works as expected without introducing any new issues.

Fixed parsing error in toxicity evaluation.

---

scripts/evaluator/aggregate.py

blend_configがない場合にaggregateがエラーになる不具合を修正

Fix blend_cfg is None case

---

configs/base_config.yaml
scripts/evaluator/jaster.py

- Include jmmlu_robustness in run

Modify base_config

---

configs/base_config.yaml

mtbenchのデータをllm-leaderboard3に移植してpathも変更

Change mtbench path

---

scripts/evaluator/evaluate_utils/prompt.py

swallowのMSモデルにその他のinstruct-v1モデル用の処理が適用されないように変更

Fix Swallow eos_token

---

scripts/evaluator/evaluate_utils/formatter.py
scripts/evaluator/evaluate_utils/prompt.py
scripts/evaluator/evaluate_utils/robustness.py

- robustnessのスコアの算出方法を修正
- symbolとincorrectの変換のバグを修正

Fix robustness

---

configs/base_config.yaml

mgsmで数字だけを答えるようにプロンプトを変更したものをuploadし、v6としています。
合わせてbase_configにてjasterのバージョンをv6に上げました。

update mgsm prompt

---

scripts/evaluator/jbbq.py

format errorが生じる割合を表示するように修正
全ての出力がformat errorの場合のハンドリングを追加
N_non_unknown_outputが0の場合にNoneにするように修正

Add format error ratio and hadling

---

configs/config-ELYZA-Llama-3-ELYZA-JP-8B.yaml

Added YAML file for elyza/Llama-3-ELYZA-JP-8B.

Added YAML for elyza/Llama-3-ELYZA-JP-8B.

---

scripts/data_uploader/upload_jbbq.py

Add JBBQ uploader

---

blend_run_configs/README.md

- Description of blend run and resume run

Add blender readme

---

scripts/mtbench_eval.py
scripts/run_eval.py

- Implementing parallel evaluation using ThreadPoolExecutor

Add parallel evaluation to MTBench

---

scripts/evaluator/evaluate_utils/llm_async_processor.py

This pull request introduces a model-specific handling for the tokyotech-llm/Swallow-7b-instruct-v0.1 model in the _ainvoke method. The changes include:
1. Adding a new attribute `self.model_name` to store the pretrained model name or path.
2. Implementing a conditional statement to check if the model is "tokyotech-llm/Swallow-7b-instruct-v0.1".
3. For this specific model, adding a stop token "</s>" to the ainvoke call.
These changes allow for more precise control over the model's output, potentially improving the quality and consistency of the generated responses for the Swallow-7b-instruct model.
This update enhances the flexibility of our LLM processor, enabling model-specific optimizations without affecting the behavior of other models.

Add model-specific stop token for tokyotech-llm/Swallow-7b-instruct-v0.1

---

scripts/mtbench_eval.py

- Aggregate excluding -1 when creating radar table

Exclude score of -1

---

configs/config-gpt-4o-mini-2024-07-18.yaml

add config file of GPT-4o-mini

add GPT-4o mini

---

configs/config-google-gemini-1.5-pro-exp-0801.yaml

Created a config file of gemini 1.5 pro 0801.
The API needs an appropriate quota to evaluate it.

add config file of gemini 1.5 pro 0801

---

scripts/vllm_server.py

This PR enhances our vLLM integration by adding support for model quantization and the ability to use custom revisions (branches, tags, or commits) from the Hugging Face Hub.
1. Added `--quantization` option to specify the quantization method.
2. Added `--revision` option to specify a custom revision from the Hugging Face Hub.
- The quantization method is now configurable via the `quantization` parameter in the configuration.
- The Hub revision (branch, tag, or commit) can be specified using the `revision` parameter, defaulting to 'main' if not provided.
- These options are passed to the vLLM command as follows:
```python
"--quantization", str(cfg.get("quantization", None)),
"--revision", str(cfg.get("revision", 'main')),
```
1. **Reduced Memory Usage**: Quantization allows for reduced …

Support quantized models such as GPTQ.

---

README.md
configs/base_config.yaml

- Updated `README.md` to add description about JTruthfulQA including how to install JUMAN++.
- Set execution of jtruthfulqa evaluation as true in `base_config.yaml`

Yuya patch 0904

---

configs/config-Athene-V2-Agent.yaml
configs/config-Athene-V2-Chat.yaml
configs/config-Qwen2_5-32B-Instruct (1).yaml
configs/config-Qwen2_5-72B-Instruct.yaml
configs/config-chatgpt-4o-latest.yaml
configs/config-gpt-o1-preview.yaml
configs/config-xai-grok-beta.yaml

As there has been request from users, I added some YAML files to configs directory.
This will make it easier to evaluate new models.

Added some configs for new models.

---

configs/config-amazon-nova-lite-v1:0.yaml
configs/config-amazon-nova-micro-v1:0.yaml
configs/config-amazon-nova-pro-v1:0.yaml
configs/config-xai-grok-beta.yaml
scripts/evaluator/mtbench.py
scripts/fastchat/llm_judge/common.py
scripts/fastchat/llm_judge/gen_api_answer.py
scripts/fastchat/model/model_adapter.py
scripts/llm_inference_adapter.py
scripts/vllm_server.py

This PR introduces the following improvements and feature additions:  
- Added model configuration files for `amazon-nova-lite-v1:0`, `amazon-nova-micro-v1:0`, and `amazon-nova-pro-v1:0` under `configs/`.  
- Implemented inference handling for Amazon Bedrock API in `scripts/llm_inference_adapter.py`.  
- Added `chat_completion_xai` in `scripts/fastchat/llm_judge/common.py`.  
- Added support for `vllm-external` models in `vLLMAdapter` (OpenAI compatible APIs).  
- Improved LoRA model loading in `scripts/vllm_server.py`.  
- Ensured correct application of LoRA settings in `scripts/fastchat/llm_judge/common.py`.  
- Updated `scripts/evaluator/mtbench.py` to support `vllm-external`.  
- Added `chat_completion_xai` handling in `scripts/fastchat/llm_judge/gen_api_answer.py`.  
- Fixed a bug in …

Amazon Nova Support, LoRA Enhancements, and Evaluation Script Fixes

---

configs/config-alt-lhtmopt2.yaml
requirements.txt
scripts/evaluator/mtbench.py
scripts/fastchat/llm_judge/common.py
scripts/fastchat/llm_judge/gen_api_answer.py
scripts/llm_inference_adapter.py

- add configs/config-alt-lhtmopt2.yaml
- add langchain-community==0.2.3 to requirements.txt
- add alt_model support
- scripts/fastchat/llm_judge/common.py
- scripts/fastchat/llm_judge/gen_api_answer.py
- scripts/llm_inference_adapter.py

add: alt model support

---

docker-compose.yaml
generate_docker_override.sh
quick_setup.sh

Dcoker関連ファイルの修正

---

configs/base_config.yaml
scripts/evaluator/__init__.py
scripts/evaluator/hallulens.py

- データセット品質に問題があるためHallulensのnonsense_nameを除外しました（Hallulensは200問→100問に変わります）
- ハルシネーションの検出なのに実在する単語が使われてしまっています
- Hallulensのデータセットを日本語化してArtifactに上げ直しました（v1）
- hallulensを追加しました
- 評価プロンプトを日本語化しました
- Artifactのパスを修正しました
**RunのURL:**
https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/l0bd2d0g

2nd sprint hallulens日本語化

---

scripts/evaluator/evaluate_utils/llm_judge_client.py

llm_judge_client.py をgit add忘れてたので追加しました

fix: missing llm_judge_client.py

---

scripts/evaluator/aggregate.py

Here's a simple PR description in English:
```markdown
Update aggregate.py to include recently implemented benchmarks in the evaluation hierarchy.
- **Add M-IFEVAL to ALT Controllability**: M-IFEVAL scores are now included in the controllability category alongside Jaster Control
- **Add JMMLU-Pro to GLP Expert Knowledge**: JMMLU-Pro (mmlu_prox_ja) is now aggregated with JMMLU and HLE in the expert knowledge category
- **Add MT-bench coding to GLP Coding**: MT-bench coding category is now properly included in the coding evaluation alongside SWE-Bench and JHumanEval
- M-IFEVAL results are read from `m_ifeval_leaderboard_table`
- JMMLU-Pro (mmlu_prox_ja) is already included in JASTER datasets and averaged across 0-shot/few-shot
- MT-bench coding scores are normalized by dividing by 10 to …
```

update aggregate.py to include m_ifeval and MTBench coding.

---

.gitignore
config_not_in_use/config-Qwen3-14B_reasoning.yaml
configs/base_config.yaml
docker-entrypoint-vllm.sh
scripts/evaluator/bfcl.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/constants/model_config.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/model_handler/local_inference/base_oss_handler.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/model_handler/local_inference/unified_oss_fc_handler.py

* UnifiedOSSFCHandlerを追加
* vLLMの[tool calling拡張](https://docs.vllm.ai/en/stable/features/tool_calling.html)に対応したモデル用の汎用FCHandler
* vLLMにTool Parser用のオプション追加
* BFCLのOSSでmax_tokenが4096固定になっていた部分をconfig化
* bfcl_output_tableにmodelとreasoning_contentを追加

Add BFCL unified FC handler for vLLM tool-calling

---

scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/eval_checker/multi_turn_eval/multi_turn_utils.py

* BFCLのマルチターン実行時に毎回Stateが初期化される問題を修正(globalにインスタンスがあれば再初期化しないように)
* BFCLのinitial_stateで `initial_state[class_name]` を読むべきところが `initial_state` のトップ階層を渡していた問題を修正
* `{"GorillaFileSystem": {"root": {...}}`
* BFCLのモデル名に `.-/` が含まれる場合にevalが動かない問題を修正
基本的には以下の箇所を公式のコードに戻しただけです
https://github.com/ShishirPatil/gorilla/blob/main/berkeley-function-call-leaderboard/bfcl_eval/eval_checker/multi_turn_eval/multi_turn_utils.py#L43-L71
https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/6j1p0ow5

fix BFCL multiturn state and classname issue

---

config_not_in_use/config-Llama-3_1-Swallow-8B-Instruct-v0_5.yaml
config_not_in_use/config-calm3-22b-chat.yaml
scripts/evaluator/evaluate_utils/bfcl_pkg/README_nejumi4.md
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/constants/default_prompts.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/constants/model_config.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/model_handler/local_inference/unified_oss_jsonschema_handler.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/model_handler/utils.py
scripts/llm_inference_adapter.py

* Structured Outputを使ってTool Call非対応モデルで構造化出力に対応する `UnifiedOSSJsonSchemaHandler` を実装
* ↑対応のためOpenAI(Chat Completion)の方もparse APIに対応
* BFCLのREADMEにOSS周りの実装を追記
Llama-3.1-Swallow-8B-Instruct-v0.5 https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/ueeo1ufi
calm3-22b https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/s7rdxo8g

implement UnifiedOSSJsonSchemaHandler

---

scripts/evaluator/evaluate_utils/bfcl_pkg/README_nejumi4.md
scripts/translation/bfcl_shuffle_problem_and_answer.py
scripts/translation/bfcl_translation.py

This pull request introduces updates to the BFCL dataset processing and translation pipeline, including adjustments to dataset details and file paths. The changes aim to enhance dataset management and streamline file processing for translations.
* [`scripts/evaluator/evaluate_utils/bfcl_pkg/README_nejumi4.md`](diffhunk://#diff-45a5102ca8e21e6bef8775031fe5f31a30a7360dc0631691f9447e91c37cae51R14-R49): Expanded the dataset documentation to include detailed descriptions of BFCL dataset variants, specifying the number of questions, sampling criteria, and filtering rules for certain categories.
* [`scripts/translation/bfcl_translation.py`](diffhunk://#diff-a90aa25b9efa8c1862fcb47b6fe47412ba701a3c3f749c13e48d26b9ea116b8fL111-R118): Updated the input and output directory paths for BFCL JSON files …

add translation related files
