wandb/llm-leaderboard

scripts/run_eval.py

This pull request addresses a minor bug fix in the configuration file handling and enhances the support for the wandb launch command.
- Fixed a bug that caused configuration file parsing to fail under certain conditions.
- Improved the robustness of the configuration file loading process during wandb launch execution.
In the previous implementation, users encountered an issue where wandb launch would fail to execute properly due to configuration file loading errors, especially when referencing specific commits in a remote repository that could not be found.
- Found and Fixed some small bugs related to `cfg`.
These changes will affect users who run jobs using the wandb launch command, particularly those specifying commits from remote repositories, as they can now expect more stable …

Yuya patch 0124 3

---

configs/gpt3.5turbo.yaml
configs/mistral7b.yaml

This PR introduces test configurations for two models: `gpt-3.5-turbo` and `mistralai/Mistral-7B-Instruct-v0.2`. The purpose of these configurations is to facilitate pre-PR testing for both commercial APIs and OpenLLMs. By enabling tests against these configurations, we aim to streamline the review process by including links to the WandB runs in the PR comments, making it easier for reviewers to assess the changes.
- Added `gpt3.5turbo.yaml` for testing with the `gpt-3.5-turbo` model.
- Added `mistral7b.yaml` for testing with the `mistralai/Mistral-7B-Instruct-v0.2` model.
- Configurations are designed to support both commercial API and OpenLLM testing scenarios.
- WandB integration is configured to log runs under the `wandb-japan` entity for both configurations, facilitating easy …

Add Test Configurations for gpt-3.5-turbo and Mistral-7B Models

---

configs/config_template.yaml
scripts/mtbench_eval.py

Adds `cfg.mtbench.use_azure` config entry in order to use Azure OpenAI Service in MT bench.
This PR requires a fix to FastChat:  https://github.com/wandb/FastChat/pull/25

Add cfg.mtbench.use_azure

---

configs/config-llama-3-8b-instruct.yaml
configs/config_prototype.yaml
scripts/run_eval.py
scripts/toxicity_eval.py

この PR では、事前に取得した toxicity データセットのサブセットを使用して toxicity 評価を導入します。この評価では、有害な入力に対するモデルの応答を評価し、様々なカテゴリに基づいてスコアを提供します。
変更内容:
1.  `config_prototype.yaml` に toxicity 評価に必要な設定を追加しました。
2. `scripts/toxicity_eval.py` に `toxicity_evaluate()` 関数を実装し、toxicity 評価プロセスを処理するようにしました。
- toxicity データセットのアーティファクトから質問をロードします。このアーティファクトはPrivate Projectに紐づけることで一般への公開は控えます。
- 並列処理を使用してモデルの回答を生成します。
- アーティファクトから judge prompts をロードします。
- judge モデルを使用してモデルの応答を評価し、スコアを抽出します。
- 結果を pd.DataFrame/wandb.Table に変換し、ログに記録します。
3. `scripts/run_eval.py` を更新し、toxicity 評価を含めるようにしました。
toxicity 評価の結果は、以下のテーブルにログ記録されます:
- `toxicity_output_table`: `visualize_ids` で指定された質問 ID を含むサンプル出力テーブル。内容が過激なケースもあるため、比較的問題が少ないレコードを選んでテーブルとして可視化します。
- `toxicity_leaderboard_table`: 各カテゴリのスコアと全体の平均スコアを示すリーダーボードテーブル。
- `toxicity_radar_table`: …

Added Toxicity Evaluation

---

requirements.txt
scripts/run_eval.py

この PR では、scripts/run_eval.pyに引数を渡すことで任意のconfigsディレクトリ以下の任意のyamlファイルで評価を実行できる機能を導入します。
変更内容:
- `scripts/run_eval.py` に引数を与えられるようにしました。`-c`ではファイル名を渡すことができます。引数には拡張子は不要です。`-s`ではconfigsディレクトリ以下の全てのyamlファイルから矢印キーでの選択が可能です。また、config周りの冗長な処理を削除しました。
- `requirements.txt`にquestionaryライブラリを追加しました。シンプルなライブラリなので依存関係の心配はありません。
この追加により、config.yamlへのコピペ作業から解放されます。

-cでconfigのファイル名を指定できる機能を追加。-sでconfigを選択できる機能を追加

---

scripts/evaluator/evaluate_utils/llm_async_processor.py
scripts/llm_inference_adapter.py

Googleのみ、invokeでmax_tokensを受け取らないのでインスタンスのmax_tokensを上書きするように変更

googleのmax_tokensのエラー対応

---

configs/base_config.yaml
requirements.txt
scripts/aggregate.py
scripts/evaluator/jaster.py
scripts/toxicity_eval.py
scripts/utils.py

1. Updated the toxicity dataset artifact to use the full dataset instead of a subset. The artifact path has been updated in `configs/base_config.yaml`.
2. Improved the `aggregate.py` script:
- Added a new function `calculate_combined_means()` to calculate the combined means of columns from jaster, mtbench, and other datasets.
- Updated the leaderboard table calculations to use the new `calculate_combined_means()` function for various GLP and ALT metrics.
- Fixed some typos and formatting issues.
3. Modified the `jaster.py` script to calculate the average scores for JMMLU categories in both the regular and control leaderboard tables.
4. Enhanced the `toxicity_eval.py` script:
- Increased the retry attempts and wait time for the `judge_extract_scores()` function to handle potential network …

Aggregate Results and Update Toxicity Dataset and Evaluation

---

configs/config-Meta-Llama-3-70B-Instruct.yaml
configs/config-Mixtral-8x7B-Instruct-v0-1.yaml
configs/config-Qwen1-5-72B-Chat.yaml
configs/config-Yi-34B-Chat.yaml
configs/config-llm-jp-13b-instruct-full-dolly-ichikara_004_001_single-oasst-oasst2-v2-0.yaml
scripts/vllm_server.py

- context lengthが短いモデル向けにmax-model-lenのデフォルト値を2048に設定しました。
- 複数のGPUを有効化できるようにmodel parallelの引数を追加しました。

fix around max-model-len and model parallel

---

scripts/evaluator/evaluate_utils/prompt.py
scripts/evaluator/jbbq.py

num_few_shotsが2の場合の2設定を加えた
具体的には（neg, amb）(nonneg, disamb）の問題が2shotoとなるように設定
また、jbbqで同じカテゴリにおいてイテレーションのたびにsystemメッセージが累積されてしまうバグを見つけたので修正

add 2shots for jbbq

---

scripts/evaluator/jaster.py

GPT-4がmmlu_enの回答にquoteを含めてしまうので、前後のクォートを除外するように変更。
この変更により他のデータセットでもscoreが上がる可能性あり

Fix around processing model output

---

scripts/aggregate.py

データセットごとのAverageが見られるようにスコア列を追加しました。

Add average columns of jaster, lctg and mtbench to leaderboard table

---

configs/config_template.yaml
scripts/run_eval.py

- Set the number of parallel processes in the config's 'parallel' parameter to parallelize the judgment process.

Add a parameter for the number of parallel judgment

---

Dockerfile
Dockerfile.vllm
configs/base_config.yaml
configs/config-Qwen3-14B.yaml
configs/config-Qwen3-14B:reasoning.yaml
configs/config-o4-mini-2025-04-16.yaml
docker-compose.yaml
docker-entrypoint-vllm.sh
quick_setup.sh
scripts/evaluator/arc_agi_2.py
scripts/evaluator/hallulens.py
scripts/evaluator/jaster.py
scripts/evaluator/jbbq.py
scripts/evaluator/jtruthfulqa.py
scripts/llm_inference_adapter.py

Reasoningモデル(vLLM/OpenAI)の対応
* llm_inference_adapterにReasoning対応の実装を追加
* OpenAI Responses APIを使うクライアントを追加
* OpenAI Chat APIのクライアントにvLLMのreasoning_contentの対応を追加
* LLMResponseクラスにreasoning_contentを返すプロパティを追加
* vLLMの起動オプションをconfigから読むように変更
* YAMLを読んで起動オプションを変更するラッパーentrypointスクリプトを追加
* デフォルトのmax_tokenやdtypeは指定しないほうがvLLMが自動でモデルに合わせてくれるので、extra_argsとして追加引数のみを指定する形式に変更
* Reasoningモデルに対応していないベンチマークの固定推論パラメータをコンフィグ可能に変更
* hallulens/jaster/jtruthfulqa/jbbqのmax_tokens,temperature,top_pなど
* o系モデルは短すぎるmax_lenと、1.0以外のtemperatureが通らないため
* 動作確認用のQwen3-14B(reasoning on/off), o4-miniのconfig追加
* その他軽微な修正
* Dockerfileのビルド順変更(ソース変更時にuv syncとjuman buildが再実行されないようにソースコード追加を後に移動)
* jtruthfulqaにtestmodeが効いてなかったのを修正
* config形式の統一
* 各ベンチマークで推論パラメータの名前や形式がバラバラなので全部generator_configとかに統一したほうがいいかも？
* 動いていないベンチマーク
* …

Reasoningモデル対応

---

scripts/evaluator/hallulens.py
uv.lock

- `scripts/evaluator/hallulens.py`: leaderboard_table作成時に`does_believe`を反転するのを失念していたので修正しました。
- `uv.lock`に重複したライブラリがあり、エラーになったので修正しました。
RunのURL:
https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/93jygbba?nw=nwusertibi

hallulens.py leaderboard集計の反転処理を修正

---

configs/base_config.yaml
scripts/data_uploader/upload_arc_agi_2.py

ARC-AGI-2の（特にローカルモデルの）推論が遅すぎるため、50example * 2 attemptにサンプリング
o3-medium(highは[公式](https://arcprize.org/blog/analyzing-o3-with-arc-agi)にもある通りレスポンスが帰ってこなくなりいつまでも終わらないので)を英語プロンプトで実行し、正解率に合わせて同じtaskのexampleが複数含まれないようにサンプリングしています。
サンプリングに使用したo3-medium: https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/91izfut7
gpt-4o: https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/433ic2g6

sampling ARC-AGI-2

---

configs/base_config.yaml
configs/config-Swallow-7b-instruct-v0.1.yaml
scripts/evaluator/evaluate_utils/__init__.py
scripts/evaluator/evaluate_utils/llm_async_processor.py
scripts/evaluator/hallulens.py
scripts/evaluator/hle.py
scripts/evaluator/mtbench.py
scripts/evaluator/toxicity.py
scripts/llm_inference_adapter.py

LLM Judge用のクライアントをAsyncOpenAIClient + LLMAsyncProcessorに統一
- toxicity, mtbench, hle, hallulensのJudge推論をLLMAsyncProcessorに統一
- hle(o3-mini使用)以外のJudge modelをgpt-4.1に変更
- toxicity, mtbenchのJudgeに正規表現を使用していた箇所をstructured outputを使用するように変更
- LLMAsyncProcessorにbatch_size, inference_intervalを引数から上書きできるように修正
- LLMAsyncProcessorのモデル特有(Swallow, Google)の処理をそれぞれconfig, GoogleClientに移動
- Judge用パラメータを同一構造で各ベンチのconfig.judge以下に設定
https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/hvnk2j99

Unify LLM-as-a-judge client to LLMAsyncProcessor

---

README.md
configs/base_config.yaml
scripts/data_uploader/upload_arc_agi.py
scripts/evaluator/__init__.py
scripts/evaluator/aggregate.py
scripts/evaluator/arc_agi.py
scripts/run_eval.py

* ARC-AGI-1のベンチマークを追加
* 2同様にo3の正解率でサンプリング50件
* ARC-AGIカテゴリで1と2の平均をスコアにするように修正
`testmode:true`, 全データセット: https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/6lq4y01y
`testmode:false`, ARC-AGIのみ全件: https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/ned86lw5

Add ARC-AGI-1 benchmark

---

configs/base_config.yaml
configs/config-example-vllm.yaml
docker-compose.yaml
docker-entrypoint-vllm.sh
pyproject.toml
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/model_handler/local_inference/base_oss_handler.py
scripts/vllm_server.py
uv.lock

* vllm configの変更
* model sectionのうちmetadata的なものを残して、vLLMの起動設定に関するものをvllmセクションに移動
* vllmの max_model_len / dtype をデフォルト未指定にして config.jsonのパラメータが優先されるように変更
* vLLMでよく使う設定値を追加
* vllmのexample configを上記に合わせて修正
* 念の為ローカルvLLM起動パスも上記の変更に対応
* 細かいfix
　　* coreheのバージョンアップでimport errorになるのでバージョンを固定
　　* BFCLでvllm-dockerを指定するとエラーになるので許可API Typeを追加
　　* VLLM_API_KEYに空環境変数を入れるとリクエストエラーになるためデフォルト値をcomposeに設定
https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev/runs/2o5z14p3

move vLLM specific configs from model to vllm section

---

configs/base_config.yaml
configs/config-example-openai-compatible.yaml
configs/config-example-vllm.yaml
configs/config-gpt-4.1-2025-04-14.yaml
configs/config-meta-llama-Llama-3.2-3B-Instruct.yaml
configs/config-meta-llama-Llama-3.3-70B-Instruct.yaml
configs/config-microsoft-phi-3-medium-128K-instruct.yaml
scripts/evaluator/bfcl.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/_llm_response_generation.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/constants/model_config.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/eval_checker/eval_runner.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/model_handler/api_inference/openrouter.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/model_handler/local_inference/base_oss_handler.py
scripts/evaluator/evaluate_utils/bfcl_pkg/bfcl/model_handler/openai_compatible_handler.py
scripts/llm_inference_adapter.py

BFCLに関するPR
Summary:  bfclのIDに, OpenRouter-FC, unified-oss-fc, unified-oss-jsonschemaを追加し、簡単に選択できるようにupdate
気になるところはあるが、動くようになったので、チームにSyncするためにPRしています
- OpenRouter-FCのAPI 
- GPT-4-1では問題なし   [Test Run ID](https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev-bfcl/runs/i8hwc6fz) 
- microsoft-phi-3-medium-128K-instruct
- response fieldがAzure OpenAIが裏側にあると受け付けられないという問題まで特定。つまり、tool use のinterfaceが同じであっても functionの渡し方などはproviderごとに調整する必要があると判明 :rotating_light: -> こうした場合には、OpenRouterや元のclassを利用する
- meta-llama/llama-3.3-70b-instruct [Test Run ID](https://wandb.ai/llm-leaderboard/nejumi-leaderboard4-dev-bfcl/runs/mjip115j)
- parallel-tool-calls　をtrueに設定。いくつかの問題では複数のtoolが返ってきている一方、スコアが0.  ["Invalid syntax. Failed to decode AST. 'str' object has no attribute 'keys'"]というエラーがある。調査する
- …

Bfcl openrouter improvement

---

configs/base_config.yaml
scripts/llm_inference_adapter.py

- ARC-AGI実行中に、gpt-4o-miniでAPI応答待ちが30秒を超えやすく、`APITimeoutError` が頻発していた。
- 既存実装ではOpenAI Chat CompletionsのHTTPタイムアウトが固定（read=30s）で、混雑・レート制限・遅延に弱い。
- 設定で柔軟に延長・調整できるよう、YAMLから上書き可能に。
- 緩めのデフォルトタイムアウトを導入（connect=10s, read=300s, write=300s, pool=30s）。
- YAMLからの上書きルール（優先順位）を実装:
- `openai.http_timeout` または `azure_openai.http_timeout` が最優先
- なければ `network.http_timeout`
- それもなければ緩めデフォルト
- 適用対象クライアント:
- `OpenAIClient`（Chat Completions）
- `OpenAIResponsesClient`（Responses API）
- `AzureOpenAIClient`（Chat Completions）
- `AzureOpenAIResponsesClient`（Responses API）
- 新規関数 `_resolve_http_timeout_from_cfg(cfg, primary_key)` を追加し、各クライアント初期化で利用。
- グローバル既定（`configs/base_config.yaml`）
```yaml
network:
http_timeout:
connect: 10.0
read: 300.0
write: 300.0
pool: 30.0
openai:
http_timeout:
connect: 10.0
read: 300.0 …
```

feat: Add YAML-configurable HTTP timeouts for OpenAI/Azure clients with relaxed defaults

---

configs/base_config.yaml

推論共通化時のmtbench, hle, toxicityのconfig変更がロールバックされていたので再適用
https://github.com/wandb/llm-leaderboard/pull/296/files#diff-6c274cd745c998c5c4673e7b0aa803182c9eef7c6b2c618ad93dffd0c3cc2960
toxicityはconfigは残ってますが、モデルによってはちょっと短いので1024に戻しています

Revert rollbacked generator config

---

configs/config-gemini-2.5-pro.yaml
configs/config-o1-2024-12-17.yaml
scripts/evaluator/jaster.py

- **背景**: JHumaneval系のコード抽出が出力形式の揺れに弱く、長文出力時の切り捨てが発生。各モデル/ベンチのトークン上限や実行設定も分散していたため統一。この現象はOpenAIのReasoningモデル（oシリーズ、GPT-5）で顕著
- **主な変更**
- **evaluator**: 多段フォールバック（JP/EN/汎用フェンス→関数定義→生出力）、正規化の廃止、`re`導入。
- **configs**:
- Gemini 2.5 Pro: batch/interval調整、thinking_budget=32768、max_tokens=65000に統一（トークン枯渇防止）。
- o1: 出力/生成上限を概ね90000へ、swebench等の各ベンチ用設定を整理（トークン枯渇防止）。
- **動作確認**
- JHumaneval系で日本語/英語/未指定フェンスの出力から正しく抽出されることを手元確認。
- 代表ベンチでエラー無くスコア計算が完了することを確認。
- **レビュー観点**
- 抽出フォールバックの順序/正規表現の妥当性
- 各ベンチマークの上限値・`run`フラグの既存運用との整合性
- **チェックリスト**
- openai/o1-2024-12-17: high-effort [[W&B Run](https://wandb.ai/llm-leaderboard/nejumi-leaderboard4/runs/2rtc9qzn)]

JHumanEval抽出の堅牢化と評価設定の見直し（max tokens拡張・Runフラグ追加）

---

scripts/evaluator/aggregate.py
uv.lock

- 修正概要
- 真実性（ALT_真実性）におけるHalluLens集計漏れ（カラム名間違い起因）を修正し、`jtruthfulqa`と`hallucination_resistance`の平均として計算されるようにしました。
- `truthfulness`サブカテゴリテーブルへHalluLensの項目を追加し、`hallulens`サブカテゴリテーブルも作成します。
- 現在の依存解決状態を`uv lock`でロックし、`uv.lock`を更新しました（コンテナ内で`uv lock`実行→`docker compose cp`でホストへ反映）。
- 変更点（主な箇所）
- `scripts/evaluator/aggregate.py`:
- `additional_flags['hallulens']`が有効かつ結果が存在する場合、`hallucination_resistance`を`truthfulness_scores`へ加算
- `create_subcategory_table(run, cfg, "hallulens", ...)`を追加
- `create_subcategory_table(run, cfg, "truthfulness", ...)`にHalluLens項目を含める
- `uv.lock`: コンテナ内で`uv lock`を実行した結果を反映
- 想定インパクト
- ALT_真実性にHalluLensが正しく寄与し、ALT全体平均にも反映されます。
- 依存関係の再現性が向上します（`uv.lock`準拠）。
- 動作確認
- HalluLensフラグ有効の設定で評価実行（[gpt-4o-mini W&B Run](https://wandb.ai/llm-leaderboard/nejumi-leaderboard4/runs/un …

 Integrate HalluLens into ALT Truthfulness (fix missing aggregation) and freeze dependencies in uv.lock
